version: '3.9'

services:
  database:
    image: postgres:latest
    environment:
      POSTGRES_USER: medicar
      POSTGRES_PASSWORD: medicar
    networks: 
      - database

  adminer:
    image: adminer:latest
    depends_on: 
      - database
    ports:
      - 8080:8080
    networks: 
      - database

  backend:
    image: python:3
    volumes: 
      - ./backend:/home/medicar
    ports:
      - 8000:8000
    tty: true
    stdin_open: true
    command: bash -c "pip install -r /home/medicar/requirements.txt && python /home/medicar/manage.py migrate && python /home/medicar/manage.py collectstatic && gunicorn medicar.wsgi --bind 0.0.0.0:8000 --chdir /home/medicar"
    networks: 
      - api
      - database

  frontend:
    image: node:lts
    volumes:
      - ./frontend:/home/medicar
    ports:
      - 4200:4200
    tty: true
    stdin_open: true
    networks:
      - api

  postwoman:
    image: liyasthomas/postwoman
    depends_on:
      - backend
    ports: 
      - 3000:3000
    networks:
      - api

networks: 
  api:
  database:
