# Generated by Django 3.2 on 2021-04-15 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('especialidades', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=64, unique=True, verbose_name='Nome')),
                ('crm', models.CharField(max_length=64, unique=True, verbose_name='CRM')),
                ('email', models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='E-mail')),
                ('telefone', models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='Telefone')),
                ('especialidades', models.ManyToManyField(to='especialidades.Especialidade', verbose_name='Especialidades')),
            ],
            options={
                'verbose_name': 'Médico(a)',
                'verbose_name_plural': 'Médicos(as)',
            },
        ),
    ]
