# Generated by Django 3.2 on 2021-04-15 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medicos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data Disponível')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicos', to='medicos.medico', verbose_name='Doutor(a)')),
            ],
            options={
                'verbose_name': 'Dia de Atendimento',
                'verbose_name_plural': 'Dias de Atendimento',
            },
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora', models.TimeField(verbose_name='Horário Disponível')),
                ('dia_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dias', to='agendas.dia', verbose_name='Dia')),
            ],
            options={
                'verbose_name': 'Horário de Atendimento',
                'verbose_name_plural': 'Horários de Atendimento',
            },
        ),
        migrations.AddConstraint(
            model_name='dia',
            constraint=models.UniqueConstraint(fields=('data', 'medico'), name='Esse(a) Médico(a) já tem uma agenda para esse dia'),
        ),
    ]
