# Generated by Django 3.2 on 2021-04-20 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agendas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='disponibilidade',
            options={'verbose_name': 'Agenda para médico', 'verbose_name_plural': 'Agendas para médicos'},
        ),
    ]
