# Generated by Django 3.2 on 2021-04-13 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('specialties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='Nome')),
                ('crm', models.CharField(max_length=64, unique=True, verbose_name='CRM')),
                ('email', models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='E-mail')),
                ('phone', models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='Telefone')),
                ('created_at', models.DateTimeField(verbose_name='Cadastrado(a) em')),
                ('updated_at', models.DateTimeField(verbose_name='Atualizado(a) em')),
                ('removed_at', models.DateTimeField(blank=True, null=True, verbose_name='Desligado(a) em')),
                ('specialties', models.ManyToManyField(to='specialties.Specialty', verbose_name='Especialidades')),
            ],
            options={
                'verbose_name': 'Médico(a)',
                'verbose_name_plural': 'Médicos(as)',
            },
        ),
    ]
