# Generated by Django 3.2 on 2021-04-13 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
        ('calendars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workday',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctors', to='doctors.doctor', verbose_name='Doutor(a)'),
        ),
    ]
