# Generated by Django 3.2 on 2021-04-13 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0002_alter_workday_doctor'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='workday',
            constraint=models.UniqueConstraint(fields=('date', 'doctor'), name='Unique Doctor Date'),
        ),
    ]
