# Generated by Django 3.2 on 2021-04-13 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='Nome')),
                ('created_at', models.DateTimeField(verbose_name='Criada em')),
                ('updated_at', models.DateTimeField(verbose_name='Atualizada em')),
                ('removed_at', models.DateTimeField(blank=True, null=True, verbose_name='Removida em')),
            ],
            options={
                'verbose_name': 'Especialidade',
                'verbose_name_plural': 'Especialidades',
            },
        ),
    ]
